name: crystalcodegen-test/new10
author:
  name: Chris Tate
  email: test@crystal.sh
  url: 'http://crystalcodegen.com'
copyright: 2015 Chris Tate
description: Test
url: 'http://example.org'
imports:
  crystal/npm: ~0.3.1
